### ISSUE TITLE
would you please send me the ace 2005 data?

### ISSUE THREAD

**Issue by lawlietAi** [mgormley/ace-data-prep#1]
sorry for my begging.i deadly need ACE data. but for my student's identity,i can't afford the fee of ACE data. please help me.
my email is 627766098@qq.com
thank you

**Comment by tangm00** [comment]
Just like you, i also need the ACE2005 data, would you please share the data?

**Comment by mgormley** [comment]
The ACE 2005 data is only available via the LDC https://catalog.ldc.upenn.edu/ldc2006t06

The intention of this repository is to provide preprocessing scripts once you've obtained the raw data through the usual channels.

**Comment by windflyhuang** [comment]
I aso need ACE 2005 dataset(english or chinese) for my research,i will pay it ,if you have the dataset ,would you please share with me the data . thank you . my email 1262686237@qq.com.

**Comment by PengLU1101** [comment]
I also need it, if you are willing to share with me, my email 1021693796@qq.com, I could share you my ontonates data.

**Comment by qq594495953** [comment]
I aso need ACE 2005 dataset(english or chinese) for my research,i will pay it ,if you have the dataset ,would you please share with me the data . thank you . my email 617314027@qq.com

**Comment by WAPING** [comment]
i need it too，thanks you anyway，my email address is 15236759872@163.com

**Comment by mgormley** [comment]
The ACE 2005 data is only available via the LDC https://catalog.ldc.upenn.edu/ldc2006t06

The intention of this repository is to provide preprocessing scripts once you've obtained the raw data through the usual channels.
