### ISSUE TITLE
Error: Could not find or load main class edu.jhu.hlt.concrete.stanford.AnnotateTokenizedConcrete

### ISSUE THREAD

**Issue by WOWNICE** [mgormley/ace-data-prep#4]
During the generation, the program gets stuck at the ace-05-comms-ptb-anno generation without any response. 

After a long time of waiting, it crashes with the following information:

Error: Could not find or load main class edu.jhu.hlt.concrete.stanford.AnnotateTokenizedConcrete

PS: my work environment is Ubuntu, Maven version is 3.5.4. 

Looking forward to any help!

**Comment by WOWNICE** [comment]
It works on my local Ubuntu workstation, but it still crashes on my remote server...

I will close the issue.

**Comment by uyaseen** [comment]
I got the same error, it is probably because of `Java version >= 9` (referred here [[1]](https://github.com/stanfordnlp/CoreNLP/issues/367), [[2]](https://github.com/stanfordnlp/CoreNLP/issues/636)). For me downgrading to `Java 8` fixed the issue.
